name: CMake CI (minimal)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build libgtest-dev
          # собрать и установить googletest из исходников пакета
          if [ -d /usr/src/googletest ]; then
            cd /usr/src/googletest
            sudo cmake -S . -B build -DBUILD_SHARED_LIBS=ON
            sudo cmake --build build --config Release -- -j$(nproc)
            sudo cmake --install build
          fi

      - name: Configure (CMake)
        run: |
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build -- -j$(nproc)

      - name: Test
        run: ctest --test-dir build/LRU --output-on-failure
